// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Event struct {
	ID        int64         `json:"id"`
	RepoID    int64         `json:"repo_id"`
	ItemType  string        `json:"item_type"`
	ItemID    sql.NullInt64 `json:"item_id"`
	EventType string        `json:"event_type"`
	Payload   []byte        `json:"payload"`
	CreatedAt time.Time     `json:"created_at"`
}

type IntegrationSubmission struct {
	ID                 int64     `json:"id"`
	RepoID             int64     `json:"repo_id"`
	BranchName         string    `json:"branch_name"`
	SourceRef          string    `json:"source_ref"`
	RefKind            string    `json:"ref_kind"`
	SourceWorktreePath string    `json:"source_worktree_path"`
	SourceSha          string    `json:"source_sha"`
	AllowNewerHead     int64     `json:"allow_newer_head"`
	RequestedBy        string    `json:"requested_by"`
	Priority           string    `json:"priority"`
	Status             string    `json:"status"`
	LastError          string    `json:"last_error"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type PublishRequest struct {
	ID            int64         `json:"id"`
	RepoID        int64         `json:"repo_id"`
	TargetSha     string        `json:"target_sha"`
	Status        string        `json:"status"`
	AttemptCount  int64         `json:"attempt_count"`
	NextAttemptAt sql.NullTime  `json:"next_attempt_at"`
	SupersededBy  sql.NullInt64 `json:"superseded_by"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type Repository struct {
	ID               int64     `json:"id"`
	CanonicalPath    string    `json:"canonical_path"`
	ProtectedBranch  string    `json:"protected_branch"`
	RemoteName       string    `json:"remote_name"`
	MainWorktreePath string    `json:"main_worktree_path"`
	PolicyVersion    string    `json:"policy_version"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
