// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO events (
	repo_id,
	item_type,
	item_id,
	event_type,
	payload
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5
)
RETURNING id, repo_id, item_type, item_id, event_type, payload, created_at
`

type AppendEventParams struct {
	RepoID    int64         `json:"repo_id"`
	ItemType  string        `json:"item_type"`
	ItemID    sql.NullInt64 `json:"item_id"`
	EventType string        `json:"event_type"`
	Payload   []byte        `json:"payload"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.RepoID,
		arg.ItemType,
		arg.ItemID,
		arg.EventType,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ItemType,
		&i.ItemID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const countQueuedIntegrationSubmissions = `-- name: CountQueuedIntegrationSubmissions :one
SELECT COUNT(*)
FROM integration_submissions
WHERE repo_id = ?1 AND status = 'queued'
`

func (q *Queries) CountQueuedIntegrationSubmissions(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueuedIntegrationSubmissions, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnfinishedIntegrationSubmissions = `-- name: CountUnfinishedIntegrationSubmissions :one
SELECT COUNT(*)
FROM integration_submissions
WHERE repo_id = ?1 AND status IN ('queued', 'running', 'blocked')
`

func (q *Queries) CountUnfinishedIntegrationSubmissions(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnfinishedIntegrationSubmissions, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnfinishedPublishRequests = `-- name: CountUnfinishedPublishRequests :one
SELECT COUNT(*)
FROM publish_requests
WHERE repo_id = ?1 AND status IN ('queued', 'running')
`

func (q *Queries) CountUnfinishedPublishRequests(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnfinishedPublishRequests, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIntegrationSubmission = `-- name: CreateIntegrationSubmission :one
INSERT INTO integration_submissions (
	repo_id,
	branch_name,
	source_ref,
	ref_kind,
	source_worktree_path,
	source_sha,
	allow_newer_head,
	requested_by,
	priority,
	status,
	last_error
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10,
	?11
)
RETURNING id, repo_id, branch_name, source_ref, ref_kind, source_worktree_path, source_sha, allow_newer_head, requested_by, priority, status, last_error, created_at, updated_at
`

type CreateIntegrationSubmissionParams struct {
	RepoID             int64  `json:"repo_id"`
	BranchName         string `json:"branch_name"`
	SourceRef          string `json:"source_ref"`
	RefKind            string `json:"ref_kind"`
	SourceWorktreePath string `json:"source_worktree_path"`
	SourceSha          string `json:"source_sha"`
	AllowNewerHead     int64  `json:"allow_newer_head"`
	RequestedBy        string `json:"requested_by"`
	Priority           string `json:"priority"`
	Status             string `json:"status"`
	LastError          string `json:"last_error"`
}

func (q *Queries) CreateIntegrationSubmission(ctx context.Context, arg CreateIntegrationSubmissionParams) (IntegrationSubmission, error) {
	row := q.db.QueryRowContext(ctx, createIntegrationSubmission,
		arg.RepoID,
		arg.BranchName,
		arg.SourceRef,
		arg.RefKind,
		arg.SourceWorktreePath,
		arg.SourceSha,
		arg.AllowNewerHead,
		arg.RequestedBy,
		arg.Priority,
		arg.Status,
		arg.LastError,
	)
	var i IntegrationSubmission
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.BranchName,
		&i.SourceRef,
		&i.RefKind,
		&i.SourceWorktreePath,
		&i.SourceSha,
		&i.AllowNewerHead,
		&i.RequestedBy,
		&i.Priority,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublishRequest = `-- name: CreatePublishRequest :one
INSERT INTO publish_requests (
	repo_id,
	target_sha,
	priority,
	status,
	attempt_count,
	next_attempt_at,
	superseded_by
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7
)
RETURNING id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
`

type CreatePublishRequestParams struct {
	RepoID        int64         `json:"repo_id"`
	TargetSha     string        `json:"target_sha"`
	Priority      string        `json:"priority"`
	Status        string        `json:"status"`
	AttemptCount  int64         `json:"attempt_count"`
	NextAttemptAt sql.NullTime  `json:"next_attempt_at"`
	SupersededBy  sql.NullInt64 `json:"superseded_by"`
}

func (q *Queries) CreatePublishRequest(ctx context.Context, arg CreatePublishRequestParams) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, createPublishRequest,
		arg.RepoID,
		arg.TargetSha,
		arg.Priority,
		arg.Status,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.SupersededBy,
	)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationSubmission = `-- name: GetIntegrationSubmission :one
SELECT id, repo_id, branch_name, source_ref, ref_kind, source_worktree_path, source_sha, allow_newer_head, requested_by, priority, status, last_error, created_at, updated_at
FROM integration_submissions
WHERE id = ?1
`

func (q *Queries) GetIntegrationSubmission(ctx context.Context, id int64) (IntegrationSubmission, error) {
	row := q.db.QueryRowContext(ctx, getIntegrationSubmission, id)
	var i IntegrationSubmission
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.BranchName,
		&i.SourceRef,
		&i.RefKind,
		&i.SourceWorktreePath,
		&i.SourceSha,
		&i.AllowNewerHead,
		&i.RequestedBy,
		&i.Priority,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishRequest = `-- name: GetPublishRequest :one
SELECT id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
FROM publish_requests
WHERE id = ?1
`

func (q *Queries) GetPublishRequest(ctx context.Context, id int64) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, getPublishRequest, id)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByPath = `-- name: GetRepositoryByPath :one
SELECT id, canonical_path, protected_branch, remote_name, main_worktree_path, policy_version, created_at, updated_at
FROM repositories
WHERE canonical_path = ?1
`

func (q *Queries) GetRepositoryByPath(ctx context.Context, canonicalPath string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByPath, canonicalPath)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.CanonicalPath,
		&i.ProtectedBranch,
		&i.RemoteName,
		&i.MainWorktreePath,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestQueuedPublishRequest = `-- name: LatestQueuedPublishRequest :one
SELECT id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
FROM publish_requests
WHERE repo_id = ?1 AND status = 'queued'
ORDER BY
	CASE priority
		WHEN 'high' THEN 0
		WHEN 'normal' THEN 1
		WHEN 'low' THEN 2
		ELSE 1
	END ASC,
	created_at DESC,
	id DESC
LIMIT 1
`

func (q *Queries) LatestQueuedPublishRequest(ctx context.Context, repoID int64) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, latestQueuedPublishRequest, repoID)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestReadyQueuedPublishRequest = `-- name: LatestReadyQueuedPublishRequest :one
SELECT id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
FROM publish_requests
WHERE repo_id = ?1
  AND status = 'queued'
  AND (next_attempt_at IS NULL OR next_attempt_at <= ?2)
ORDER BY
	CASE priority
		WHEN 'high' THEN 0
		WHEN 'normal' THEN 1
		WHEN 'low' THEN 2
		ELSE 1
	END ASC,
	created_at DESC,
	id DESC
LIMIT 1
`

type LatestReadyQueuedPublishRequestParams struct {
	RepoID int64        `json:"repo_id"`
	NowUtc sql.NullTime `json:"now_utc"`
}

func (q *Queries) LatestReadyQueuedPublishRequest(ctx context.Context, arg LatestReadyQueuedPublishRequestParams) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, latestReadyQueuedPublishRequest, arg.RepoID, arg.NowUtc)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, repo_id, item_type, item_id, event_type, payload, created_at
FROM events
WHERE repo_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListEventsParams struct {
	RepoID     int64 `json:"repo_id"`
	LimitCount int64 `json:"limit_count"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.RepoID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.ItemType,
			&i.ItemID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, repo_id, item_type, item_id, event_type, payload, created_at
FROM events
WHERE repo_id = ?1 AND id > ?2
ORDER BY created_at ASC, id ASC
LIMIT ?3
`

type ListEventsAfterParams struct {
	RepoID     int64 `json:"repo_id"`
	AfterID    int64 `json:"after_id"`
	LimitCount int64 `json:"limit_count"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter, arg.RepoID, arg.AfterID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.ItemType,
			&i.ItemID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForItemDesc = `-- name: ListEventsForItemDesc :many
SELECT id, repo_id, item_type, item_id, event_type, payload, created_at
FROM events
WHERE repo_id = ?1
  AND item_type = ?2
  AND item_id = ?3
ORDER BY id DESC
LIMIT ?4
`

type ListEventsForItemDescParams struct {
	RepoID     int64         `json:"repo_id"`
	ItemType   string        `json:"item_type"`
	ItemID     sql.NullInt64 `json:"item_id"`
	LimitCount int64         `json:"limit_count"`
}

func (q *Queries) ListEventsForItemDesc(ctx context.Context, arg ListEventsForItemDescParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForItemDesc,
		arg.RepoID,
		arg.ItemType,
		arg.ItemID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.ItemType,
			&i.ItemID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationSubmissions = `-- name: ListIntegrationSubmissions :many
SELECT id, repo_id, branch_name, source_ref, ref_kind, source_worktree_path, source_sha, allow_newer_head, requested_by, priority, status, last_error, created_at, updated_at
FROM integration_submissions
WHERE repo_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListIntegrationSubmissions(ctx context.Context, repoID int64) ([]IntegrationSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationSubmissions, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationSubmission
	for rows.Next() {
		var i IntegrationSubmission
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.BranchName,
			&i.SourceRef,
			&i.RefKind,
			&i.SourceWorktreePath,
			&i.SourceSha,
			&i.AllowNewerHead,
			&i.RequestedBy,
			&i.Priority,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationSubmissionsByStatus = `-- name: ListIntegrationSubmissionsByStatus :many
SELECT id, repo_id, branch_name, source_ref, ref_kind, source_worktree_path, source_sha, allow_newer_head, requested_by, priority, status, last_error, created_at, updated_at
FROM integration_submissions
WHERE repo_id = ?1 AND status = ?2
ORDER BY created_at ASC, id ASC
`

type ListIntegrationSubmissionsByStatusParams struct {
	RepoID int64  `json:"repo_id"`
	Status string `json:"status"`
}

func (q *Queries) ListIntegrationSubmissionsByStatus(ctx context.Context, arg ListIntegrationSubmissionsByStatusParams) ([]IntegrationSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationSubmissionsByStatus, arg.RepoID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationSubmission
	for rows.Next() {
		var i IntegrationSubmission
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.BranchName,
			&i.SourceRef,
			&i.RefKind,
			&i.SourceWorktreePath,
			&i.SourceSha,
			&i.AllowNewerHead,
			&i.RequestedBy,
			&i.Priority,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishRequests = `-- name: ListPublishRequests :many
SELECT id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
FROM publish_requests
WHERE repo_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListPublishRequests(ctx context.Context, repoID int64) ([]PublishRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPublishRequests, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishRequest
	for rows.Next() {
		var i PublishRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TargetSha,
			&i.Priority,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishRequestsByStatus = `-- name: ListPublishRequestsByStatus :many
SELECT id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
FROM publish_requests
WHERE repo_id = ?1 AND status = ?2
ORDER BY created_at ASC, id ASC
`

type ListPublishRequestsByStatusParams struct {
	RepoID int64  `json:"repo_id"`
	Status string `json:"status"`
}

func (q *Queries) ListPublishRequestsByStatus(ctx context.Context, arg ListPublishRequestsByStatusParams) ([]PublishRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPublishRequestsByStatus, arg.RepoID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishRequest
	for rows.Next() {
		var i PublishRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TargetSha,
			&i.Priority,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDelayedQueuedPublishRequest = `-- name: NextDelayedQueuedPublishRequest :one
SELECT id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
FROM publish_requests
WHERE repo_id = ?1
  AND status = 'queued'
  AND next_attempt_at IS NOT NULL
  AND next_attempt_at > ?2
ORDER BY next_attempt_at ASC, id ASC
LIMIT 1
`

type NextDelayedQueuedPublishRequestParams struct {
	RepoID int64        `json:"repo_id"`
	NowUtc sql.NullTime `json:"now_utc"`
}

func (q *Queries) NextDelayedQueuedPublishRequest(ctx context.Context, arg NextDelayedQueuedPublishRequestParams) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, nextDelayedQueuedPublishRequest, arg.RepoID, arg.NowUtc)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextQueuedIntegrationSubmission = `-- name: NextQueuedIntegrationSubmission :one
SELECT id, repo_id, branch_name, source_ref, ref_kind, source_worktree_path, source_sha, allow_newer_head, requested_by, priority, status, last_error, created_at, updated_at
FROM integration_submissions
WHERE repo_id = ?1 AND status = 'queued'
ORDER BY
	CASE priority
		WHEN 'high' THEN 0
		WHEN 'normal' THEN 1
		WHEN 'low' THEN 2
		ELSE 1
	END ASC,
	created_at ASC,
	id ASC
LIMIT 1
`

func (q *Queries) NextQueuedIntegrationSubmission(ctx context.Context, repoID int64) (IntegrationSubmission, error) {
	row := q.db.QueryRowContext(ctx, nextQueuedIntegrationSubmission, repoID)
	var i IntegrationSubmission
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.BranchName,
		&i.SourceRef,
		&i.RefKind,
		&i.SourceWorktreePath,
		&i.SourceSha,
		&i.AllowNewerHead,
		&i.RequestedBy,
		&i.Priority,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetPublishRequestForRetry = `-- name: ResetPublishRequestForRetry :one
UPDATE publish_requests
SET status = 'queued',
	attempt_count = 0,
	next_attempt_at = NULL,
	superseded_by = NULL,
	updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
`

func (q *Queries) ResetPublishRequestForRetry(ctx context.Context, id int64) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, resetPublishRequestForRetry, id)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const schedulePublishRetry = `-- name: SchedulePublishRetry :one
UPDATE publish_requests
SET status = 'queued',
	attempt_count = ?1,
	next_attempt_at = ?2,
	superseded_by = NULL,
	updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
RETURNING id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
`

type SchedulePublishRetryParams struct {
	AttemptCount  int64        `json:"attempt_count"`
	NextAttemptAt sql.NullTime `json:"next_attempt_at"`
	ID            int64        `json:"id"`
}

func (q *Queries) SchedulePublishRetry(ctx context.Context, arg SchedulePublishRetryParams) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, schedulePublishRetry, arg.AttemptCount, arg.NextAttemptAt, arg.ID)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeOlderQueuedPublishRequests = `-- name: SupersedeOlderQueuedPublishRequests :exec
UPDATE publish_requests
SET status = 'superseded', superseded_by = ?1, updated_at = CURRENT_TIMESTAMP
WHERE repo_id = ?2 AND status = 'queued' AND id <> ?1
`

type SupersedeOlderQueuedPublishRequestsParams struct {
	KeepID sql.NullInt64 `json:"keep_id"`
	RepoID int64         `json:"repo_id"`
}

func (q *Queries) SupersedeOlderQueuedPublishRequests(ctx context.Context, arg SupersedeOlderQueuedPublishRequestsParams) error {
	_, err := q.db.ExecContext(ctx, supersedeOlderQueuedPublishRequests, arg.KeepID, arg.RepoID)
	return err
}

const updateIntegrationSubmissionPriority = `-- name: UpdateIntegrationSubmissionPriority :one
UPDATE integration_submissions
SET priority = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
RETURNING id, repo_id, branch_name, source_ref, ref_kind, source_worktree_path, source_sha, allow_newer_head, requested_by, priority, status, last_error, created_at, updated_at
`

type UpdateIntegrationSubmissionPriorityParams struct {
	Priority string `json:"priority"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateIntegrationSubmissionPriority(ctx context.Context, arg UpdateIntegrationSubmissionPriorityParams) (IntegrationSubmission, error) {
	row := q.db.QueryRowContext(ctx, updateIntegrationSubmissionPriority, arg.Priority, arg.ID)
	var i IntegrationSubmission
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.BranchName,
		&i.SourceRef,
		&i.RefKind,
		&i.SourceWorktreePath,
		&i.SourceSha,
		&i.AllowNewerHead,
		&i.RequestedBy,
		&i.Priority,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIntegrationSubmissionStatus = `-- name: UpdateIntegrationSubmissionStatus :one
UPDATE integration_submissions
SET status = ?1, last_error = ?2, updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
RETURNING id, repo_id, branch_name, source_ref, ref_kind, source_worktree_path, source_sha, allow_newer_head, requested_by, priority, status, last_error, created_at, updated_at
`

type UpdateIntegrationSubmissionStatusParams struct {
	Status    string `json:"status"`
	LastError string `json:"last_error"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateIntegrationSubmissionStatus(ctx context.Context, arg UpdateIntegrationSubmissionStatusParams) (IntegrationSubmission, error) {
	row := q.db.QueryRowContext(ctx, updateIntegrationSubmissionStatus, arg.Status, arg.LastError, arg.ID)
	var i IntegrationSubmission
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.BranchName,
		&i.SourceRef,
		&i.RefKind,
		&i.SourceWorktreePath,
		&i.SourceSha,
		&i.AllowNewerHead,
		&i.RequestedBy,
		&i.Priority,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublishRequestStatus = `-- name: UpdatePublishRequestStatus :one
UPDATE publish_requests
SET status = ?1, superseded_by = ?2, next_attempt_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
RETURNING id, repo_id, target_sha, priority, status, attempt_count, next_attempt_at, superseded_by, created_at, updated_at
`

type UpdatePublishRequestStatusParams struct {
	Status       string        `json:"status"`
	SupersededBy sql.NullInt64 `json:"superseded_by"`
	ID           int64         `json:"id"`
}

func (q *Queries) UpdatePublishRequestStatus(ctx context.Context, arg UpdatePublishRequestStatusParams) (PublishRequest, error) {
	row := q.db.QueryRowContext(ctx, updatePublishRequestStatus, arg.Status, arg.SupersededBy, arg.ID)
	var i PublishRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetSha,
		&i.Priority,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (
	canonical_path,
	protected_branch,
	remote_name,
	main_worktree_path,
	policy_version
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5
)
ON CONFLICT(canonical_path) DO UPDATE SET
	protected_branch = excluded.protected_branch,
	remote_name = excluded.remote_name,
	main_worktree_path = excluded.main_worktree_path,
	policy_version = excluded.policy_version,
	updated_at = CURRENT_TIMESTAMP
RETURNING id, canonical_path, protected_branch, remote_name, main_worktree_path, policy_version, created_at, updated_at
`

type UpsertRepositoryParams struct {
	CanonicalPath    string `json:"canonical_path"`
	ProtectedBranch  string `json:"protected_branch"`
	RemoteName       string `json:"remote_name"`
	MainWorktreePath string `json:"main_worktree_path"`
	PolicyVersion    string `json:"policy_version"`
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, upsertRepository,
		arg.CanonicalPath,
		arg.ProtectedBranch,
		arg.RemoteName,
		arg.MainWorktreePath,
		arg.PolicyVersion,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.CanonicalPath,
		&i.ProtectedBranch,
		&i.RemoteName,
		&i.MainWorktreePath,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
